### ISSUE TITLE
Compilation error: zpiv/accumulatorcheckpoints.cpp:6:10: fatal error: accumulatorcheckpoints.json.h: No such file or directory

### ISSUE THREAD

**Issue by LinuxETC** [beaconcrypto/beacon#1]
Received the following compilation error noted below.  System is Ubuntu 18.04.
Code used was the latest from https://github.com/beaconcrypto/beacon/archive/v3.4.tar.gz
```
zpiv/accumulatorcheckpoints.cpp:6:10: fatal error: accumulatorcheckpoints.json.h: No such file or directory
 #include "accumulatorcheckpoints.json.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:5082: recipe for target 'zpiv/libbitcoin_common_a-accumulatorcheckpoints.o' failed
make[2]: *** [zpiv/libbitcoin_common_a-accumulatorcheckpoints.o] Error 1
make[2]: Leaving directory '/tmp/BECN-v3.4.0/src'
Makefile:9482: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/BECN-v3.4.0/src'
Makefile:748: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

**Comment by LinuxETC** [comment]
Update:
Do a 

`git clone https://github.com/beaconcrypto/beacon.git` 

will pull an updated version of the source code.  Compiling from there works on Ubuntu 18.04.

Recommendation:
Update the https://github.com/beaconcrypto/beacon/archive/v3.4.tar.gz file appropriately.
